language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE lake;"
  - mysql -u root -e "CREATE USER 'lake'@'localhost' IDENTIFIED BY 'lake';"
  - mysql -u root -e "GRANT ALL ON lake.* TO 'lake'@'localhost';"
  - mysql -u root lake < tests/dump.sql

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'

script: phpunit tests/Main.php
