language: php

services:
  - mysql

before_script:
  - mysql -u root -e "CREATE DATABASE lake;"
  - mysql -u root -e "CREATE USER 'lake'@'localhost' IDENTIFIED BY 'lake';"
  - mysql -u root -e "GRANT ALL ON lake.* TO 'lake'@'localhost';"
  - mysql -u root lake < tests/dump.sql
  # Install composer
  - curl -sS https://getcomposer.org/installer | php
  # Install phpunit
  - ./composer.phar require --dev phpunit/phpunit ^9
  - ./vendor/bin/phpunit --version


php:
  - '8.0'
  - '8.1'

script: ./vendor/bin/phpunit
